### ISSUE TITLE
Did you use the Ameba official 'amebad_image_tool' executable file?

### ISSUE THREAD

**Issue by xidameng** [jojoling/ameba_bw16_autoflash#1]
Hi

After browsing through your src, I didn't seem to find the use of `amebad_image_tool` in your code, may I know how you upload the firmware images to Ameba without it?

**Comment by ajsb85** [comment]
He is a hacker.
To make re-engineering he should analyze the data transferred or decompile the `amebad_image_tool `
Or he just gets the NDA with Realtek.
Nobody knows.

**Comment by xidameng** [comment]
> He is a hacker.
> To make re-engineering he should analyze the data transferred or decompile the `amebad_image_tool `
> Or he just gets the NDA with Realtek.
> Nobody knows.

He is a super hacker and advanced maker, he basically decode the entire UART transmission and using his decoded logic he re-write his own `image_tool`,,,  amazing skills, he even explained his entire working process in a live stream which can be replayed here  https://www.facebook.com/groups/AmebaIoT/permalink/2950589368529213/
